##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## scrpit
##

all : $(NAME)

SRC = 		do_op.c

NAME = do-op

$(NAME) =
		gcc -o $(NAME) $(SRC)

clean :
		rm -f $(SRC)

fclean :
		clean
		rm -f $(NAME)

re :
		fclean all
