#!/usr/bin/env python3

# ã

import sys
import math

number_values = 0
arithmetic_mean = 0
harmonic_mean = 0
standard_deviation = 0

def calculate(number_values, arithmetic_mean, harmonic_mean, standard_deviation, input_val):
    values = []
    total_arithm = arithmetic_mean * number_values

    values.append(number_values + 1)
    values.append((total_arithm + input_val) / values[0])
    values.append(values[0] / ((1 / input_val) + (number_values / harmonic_mean)))
    values.append(math.sqrt(((((standard_deviation ** 2 + arithmetic_mean ** 2) * number_values) + input_val ** 2) / values[0]) - values[1] ** 2))

    return values

def input_value(number_values, arithmetic_mean, harmonic_mean, standard_deviation):
    entry = ""
    values = [number_values, arithmetic_mean, harmonic_mean, standard_deviation]

    while entry != "END":
        entry = input("Enter next value: ")
        if entry != "END":
            try:
                entry = float(entry)
            except:
                sys.stderr.write("Value is not a float.\n")
                exit(84)
            if entry < 0.0:
                sys.stderr.write("Value cannot be negative.\n")
                exit(84)
            root_mean_square = math.sqrt((((math.pow(values[3], 2) + math.pow(values[1], 2)) * (values[0])) + math.pow(entry, 2)) / (values[0] + 1))

            values = calculate(values[0], values[1], values[2], values[3], entry)
            print("\tNumber of values:\t%i" % values[0])
            print("\tStandard deviation:\t%.2f" % values[3])
            print("\tArithmetic mean:\t%.2f" % values[1])
            print("\tRoot mean square:\t%.2f" % (root_mean_square))
            print("\tHarmonic mean:\t%.2f" % values[2])

if len(sys.argv) != 2 and len(sys.argv) != 5:
    sys.stderr.write("Wrong launch. Please type ./206neutrinos -h for help.\n")
    exit(84)
else:
    if len(sys.argv) == 2 and sys.argv[1] == "-h":
        print("USAGE")
        print("\t./206neutrinos n a h sd\n")
        print("DESCRIPTION")
        print("\tn\tnumber of values")
        print("\ta\tarithmetic mean")
        print("\th\tharmonic mean")
        print("\tsd\tstandard deviation")
        exit(0)
    elif len(sys.argv) == 5:
        try:
            number_values = int(sys.argv[1])
            arithmetic_mean = int(sys.argv[2])
            harmonic_mean = int(sys.argv[3])
            standard_deviation = int(sys.argv[4])
            if number_values < 0 or arithmetic_mean < 0 or harmonic_mean < 0 or standard_deviation < 0:
                sys.stderr.write("Values must be positive. Please type ./206neutrinos -h for help.\n")
                exit(84)
        except:
            sys.stderr.write("Arguments must be integer. Please type ./206neutrinos -h for help.\n")
            exit(84)
        input_value(number_values, arithmetic_mean, harmonic_mean, standard_deviation)
        exit(0)
    else:
        sys.stderr.write("Wrong launch. Please type ./206neutrinos -h for help.\n")
        exit(84)