#!/usr/bin/env bash

virtualenv . -p /usr/bin/python3
source bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install flask
python3 -m pip install pymysql

cat epytodo.sql | mysql -u root -p

./run.py