##
## EPITECH PROJECT, 2021
## B-OOP-400-MPL-4-1-arcade-richard.habimana
## File description:
## Makefile
##

all:
	make -C pacman
	make -C nibbler

clean:
	make clean -C pacman
	make clean -C nibbler

fclean:
	make fclean -C pacman
	make fclean -C nibbler

re : fclean all