version: "3.9"
services:
  jenkins:
    #image jenkins/jenkins:latest
    build: .
    ports:
      - 8080:8080
    environment:
      CASC_JENKINS_CONFIG: /jenkins.yml
      USER_CHOCOLATEEN_PASSWORD: test
      USER_VAUGIE_G_PASSWORD: test
      USER_I_DONT_KNOW_PASSWORD: test
      USER_NASSO_PASSWORD: test
    volumes:
      - ./my_marvin.yml:/jenkins.yml
      - ./job_dsl.groovy:/job_dsl.groovy