##
## EPITECH PROJECT, 2021
## B-OOP-400-MPL-4-1-arcade-richard.habimana
## File description:
## Makefile
##

all:
	make -C ncurse
	make -C sdl2
	make -C sfml

clean:
	make clean -C ncurse
	make clean -C sdl2
	make clean -C sfml

fclean:
	make fclean -C ncurse
	make fclean -C sdl2
	make fclean -C sfml

re : fclean all